# Generated by Django 5.2.6 on 2025-11-26 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_webhook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='webhook_url',
        ),
        migrations.CreateModel(
            name='AdminWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(help_text='URL to receive webhook notifications')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this webhook')),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Slack notifications')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_user_registered', models.BooleanField(default=True, help_text='Notify when new users register')),
                ('notify_subscription_created', models.BooleanField(default=True, help_text='Notify when subscriptions are created')),
                ('notify_subscription_updated', models.BooleanField(default=True, help_text='Notify when subscriptions are updated')),
                ('admin_user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Webhook',
                'verbose_name_plural': 'Admin Webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
