# Generated by Django 5.2.6 on 2025-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_webhook_url_adminwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL to receive notifications (e.g., when API limits are hit)', null=True),
        ),
    ]
