# Generated by Django 5.2.6 on 2025-11-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_webhook_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminWebhook',
        ),
    ]
