# Generated by Django 5.2.6 on 2025-12-03 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_invoice'),
        ('subscriptions', '0003_add_plan_overage_rate_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='meterevent',
            name='event_id',
            field=models.CharField(db_index=True, help_text='Idempotency key', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='meterevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='meterevent',
            index=models.Index(fields=['user', 'feature', '-timestamp'], name='metering_me_user_id_81cce1_idx'),
        ),
        migrations.AddIndex(
            model_name='meterevent',
            index=models.Index(fields=['user', '-timestamp'], name='metering_me_user_id_56dd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='meterevent',
            index=models.Index(fields=['timestamp'], name='metering_me_timesta_e55aa0_idx'),
        ),
    ]
